import sys
import json
import random

def get_recommendations(user_id):
    # This is a mock AI recommendation engine utilizing Python.
    # In a real-world scenario, you could use pandas, scikit-learn, etc.
    # to evaluate user read history and output predicted preferences.
    
    # Mock book IDs available in db
    all_books = [1, 2, 3, 4, 5]
    
    # Simulate some logic dependent on the user ID
    random.seed(int(user_id) + 42)
    
    # Select 3 random book IDs for recommendations
    recommended_ids = random.sample(all_books, 3)
    
    # Returning JSON data to be parsed by PHP
    print(json.dumps({
        "status": "success",
        "user_id": user_id,
        "recommended_book_ids": recommended_ids,
        "message": "AI Recommendations generated by Python Engine."
    }))

if __name__ == "__main__":
    if len(sys.argv) > 1:
        user_id = sys.argv[1]
        get_recommendations(user_id)
    else:
        print(json.dumps({"status": "error", "message": "No User ID provided"}))
